name: pull-request

env:
  MIN_SUPPORTED_RUST_VERSION: "1.64.0"

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: agenthunt/conventional-commit-checker-action@v1.0.0
        continue-on-error: true
        with:
          pr-body-regex: ".*"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.MIN_SUPPORTED_RUST_VERSION }}
          profile: minimal
          components: clippy,rustfmt
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets
